baseurl = "https://mignamis.github.io/"
languageCode = "it"
title = "WebASD"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "webasd"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-25273359-4"
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."


[params]
	author = "Simone Mignami"
	description = "Consigli utili per un web accessibile."
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "accessibilità, web, tecnologia, WAI-ARIA, HTML5, screen reader"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/logo.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = ""

	headerText = "Web Accessibile Senza Difficoltà Contiene tutto quello che devi sapere per curare l'accessibilità."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "simone.mig29@gmail.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = ""
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
